###
GET http://localhost:5216/api/users

###
GET http://localhost:5216/api/users/3

###
POST http://localhost:5216/api/users    
Content-Type: application/json

{

  "name": "David",
  "email": "david@example.com"
}

###
PUT http://localhost:5216/api/users/3
Content-Type: application/json

{
  "name": "Charlie Updated",
  "email": "charlie@updated.com"
  }

###
DELETE http://localhost:5216/api/users/3